// src/listings/businesses.ts

export interface Business {
  id: number;
  title: string;
  description: string;
  category: string;
  location: string;
  rating: number;
  featured?: boolean;
  trending?: boolean;
  image: string;
  slug: string;
  price?: number;
}

export const listingsData: Business[] = [
  {
    id: 1,
    title: "FixIt Plumbing Services",
    description: "24/7 plumbing repair and water system installation in Lagos.",
    category: "Plumbers",
    location: "Lagos, Nigeria",
    rating: 4.6,
    featured: true,
    trending: true,
    image: "https://source.unsplash.com/600x400/?plumber",
    slug: "fixit-plumbing-services",
    price: 20000,
  },
  {
    id: 2,
    title: "Spark Electrical Works",
    description: "Professional electrical wiring and repair services.",
    category: "Electricians",
    location: "Abuja, Nigeria",
    rating: 4.8,
    featured: true,
    trending: false,
    image: "https://source.unsplash.com/600x400/?electrician",
    slug: "spark-electrical-works",
    price: 15000,
  },
  {
    id: 3,
    title: "Bright Future Solar",
    description: "Affordable solar panel installation and maintenance.",
    category: "Solar",
    location: "Port Harcourt, Nigeria",
    rating: 4.9,
    featured: false,
    trending: true,
    image: "https://source.unsplash.com/600x400/?solar",
    slug: "bright-future-solar",
    price: 120000,
  },
  {
    id: 4,
    title: "Green Landscaping",
    description: "Beautiful landscaping and garden maintenance.",
    category: "Landscaping",
    location: "Enugu, Nigeria",
    rating: 4.3,
    featured: false,
    trending: false,
    image: "https://source.unsplash.com/600x400/?landscaping",
    slug: "green-landscaping",
    price: 35000,
  },
  {
    id: 5,
    title: "QuickFix IT Solutions",
    description: "Laptop and desktop repair specialists.",
    category: "IT Services",
    location: "Kano, Nigeria",
    rating: 4.7,
    featured: true,
    trending: true,
    image: "https://source.unsplash.com/600x400/?computer",
    slug: "quickfix-it-solutions",
    price: 45000,
  },
  {
    id: 6,
    title: "Taste of Naija",
    description: "Local Nigerian dishes served fresh daily.",
    category: "Restaurants",
    location: "Lagos, Nigeria",
    rating: 4.5,
    featured: true,
    trending: true,
    image: "https://source.unsplash.com/600x400/?restaurant,food",
    slug: "taste-of-naija",
    price: 8000,
  },
  {
    id: 7,
    title: "Event360 Planners",
    description: "Event planning, wedding coordination, and corporate functions.",
    category: "Events",
    location: "Abuja, Nigeria",
    rating: 4.9,
    featured: true,
    trending: true,
    image: "https://source.unsplash.com/600x400/?event,party",
    slug: "event360-planners",
    price: 500000,
  },
  {
    id: 8,
    title: "Tech Jobs Hub",
    description: "Connecting Nigerian tech talent with top employers.",
    category: "Jobs",
    location: "Remote",
    rating: 4.8,
    featured: false,
    trending: true,
    image: "https://source.unsplash.com/600x400/?office,work",
    slug: "tech-jobs-hub",
  },
  {
    id: 9,
    title: "Glow Beauty Spa",
    description: "Luxury spa treatments and skincare services.",
    category: "Beauty",
    location: "Lagos, Nigeria",
    rating: 4.6,
    featured: true,
    trending: false,
    image: "https://source.unsplash.com/600x400/?spa,beauty",
    slug: "glow-beauty-spa",
    price: 25000,
  },
  {
    id: 10,
    title: "Elite Fitness Gym",
    description: "Modern gym with personal training and wellness programs.",
    category: "Health & Fitness",
    location: "Abuja, Nigeria",
    rating: 4.7,
    featured: false,
    trending: true,
    image: "https://source.unsplash.com/600x400/?gym,fitness",
    slug: "elite-fitness-gym",
    price: 15000,
  },
  {
    id: 11,
    title: "EduSmart Academy",
    description: "After-school tutoring and online learning programs.",
    category: "Education",
    location: "Ibadan, Nigeria",
    rating: 4.4,
    featured: false,
    trending: false,
    image: "https://source.unsplash.com/600x400/?education,classroom",
    slug: "edusmart-academy",
    price: 10000,
  },
  {
    id: 12,
    title: "Naija Rides",
    description: "Affordable taxi and car hire service across Nigeria.",
    category: "Transport",
    location: "Nationwide",
    rating: 4.5,
    featured: true,
    trending: true,
    image: "https://source.unsplash.com/600x400/?taxi,car",
    slug: "naija-rides",
    price: 5000,
  },
  {
    id: 13,
    title: "Style Haven",
    description: "Trendy fashion boutique with Nigerian & international brands.",
    category: "Fashion",
    location: "Lagos, Nigeria",
    rating: 4.6,
    featured: false,
    trending: true,
    image: "https://source.unsplash.com/600x400/?fashion,clothes",
    slug: "style-haven",
    price: 20000,
  },
  {
    id: 14,
    title: "FarmFresh Groceries",
    description: "Organic fruits and vegetables delivered to your door.",
    category: "Groceries",
    location: "Port Harcourt, Nigeria",
    rating: 4.9,
    featured: true,
    trending: true,
    image: "https://source.unsplash.com/600x400/?groceries,market",
    slug: "farmfresh-groceries",
    price: 12000,
  },
  {
    id: 15,
    title: "Swift Repairs",
    description: "Fast mobile phone and gadget repairs.",
    category: "Repairs",
    location: "Enugu, Nigeria",
    rating: 4.5,
    featured: false,
    trending: false,
    image: "https://source.unsplash.com/600x400/?mobile,repair",
    slug: "swift-repairs",
    price: 10000,
  },
];
